[build]
  command = "npm ci && npm run build"
  publish = "dist/public"

# Force HTTPS
[[redirects]]
  from = "http://*elevategrowth.solutions/*"
  to = "https://www.elevategrowth.solutions/:splat"
  status = 301
  force = true

# Force www
[[redirects]]
  from = "https://elevategrowth.solutions/*"
  to = "https://www.elevategrowth.solutions/:splat"
  status = 301
  force = true
