import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen">
      <SEO 
        title="Privacy Policy | Elevate Growth Solutions"
        description="Privacy Policy for Elevate Growth Solutions. Learn how we collect, use, and protect your personal information when you use our marketing services."
      />
      <Navbar />
      
      <section className="py-16 md:py-24 bg-background">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="font-display font-semibold text-4xl md:text-5xl text-primary mb-8" data-testid="text-privacy-title">
            Privacy Policy
          </h1>
          
          <div className="space-y-8 font-serif text-foreground">
            <p className="text-lg leading-relaxed">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            
            <p className="text-lg leading-relaxed">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <div>
              <h2 className="font-display font-semibold text-2xl md:text-3xl text-primary mb-4">Interpretation and Definitions</h2>
              
              <h3 className="font-display font-semibold text-xl text-foreground mb-3 mt-6">Interpretation</h3>
              <p className="text-lg leading-relaxed">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>

              <h3 className="font-display font-semibold text-xl text-foreground mb-3 mt-6">Definitions</h3>
              <p className="text-lg leading-relaxed mb-4">For the purposes of this Privacy Policy:</p>
              <ul className="list-disc pl-6 space-y-2 text-lg">
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Elevate Growth Solutions LLC, 7533 S CENTER VIEW CT STE 210, WEST JORDAN, UT 84084.</li>
                <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li><strong>Country</strong> refers to: Utah, United States</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Website.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong>Website</strong> refers to Elevate Growth Solutions, accessible from elevategrowth.solutions</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </div>

            <div>
              <h2 className="font-display font-semibold text-2xl md:text-3xl text-primary mb-4">Collecting and Using Your Personal Data</h2>
              
              <h3 className="font-display font-semibold text-xl text-foreground mb-3 mt-6">Types of Data Collected</h3>
              
              <h4 className="font-display font-semibold text-lg text-foreground mb-3 mt-4">Personal Data</h4>
              <p className="text-lg leading-relaxed mb-3">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-lg mb-4">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Usage Data</li>
              </ul>

              <h4 className="font-display font-semibold text-lg text-foreground mb-3 mt-4">Usage Data</h4>
              <p className="text-lg leading-relaxed mb-3">
                Usage Data is collected automatically when using the Service.
              </p>
              <p className="text-lg leading-relaxed mb-3">
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
            </div>

            <div>
              <h3 className="font-display font-semibold text-xl text-foreground mb-3 mt-6">Tracking Technologies and Cookies</h3>
              <p className="text-lg leading-relaxed mb-3">
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
              </p>
            </div>

            <div>
              <h3 className="font-display font-semibold text-xl text-foreground mb-3 mt-6">Use of Your Personal Data</h3>
              <p className="text-lg leading-relaxed mb-3">The Company may use Personal Data for the following purposes:</p>
              <ul className="list-disc pl-6 space-y-2 text-lg">
                <li>To provide and maintain our Service</li>
                <li>To manage Your Account</li>
                <li>For the performance of a contract</li>
                <li>To contact You</li>
                <li>To provide You with news and special offers</li>
                <li>To manage Your requests</li>
                <li>For business transfers</li>
                <li>For other purposes such as data analysis and service improvement</li>
              </ul>
            </div>

            <div>
              <h3 className="font-display font-semibold text-xl text-foreground mb-3 mt-6">Retention of Your Personal Data</h3>
              <p className="text-lg leading-relaxed">
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
              </p>
            </div>

            <div>
              <h3 className="font-display font-semibold text-xl text-foreground mb-3 mt-6">Security of Your Personal Data</h3>
              <p className="text-lg leading-relaxed">
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
              </p>
            </div>

            <div>
              <h3 className="font-display font-semibold text-xl text-foreground mb-3 mt-6">Children's Privacy</h3>
              <p className="text-lg leading-relaxed">
                Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
              </p>
            </div>

            <div>
              <h3 className="font-display font-semibold text-xl text-foreground mb-3 mt-6">Legal Basis for Processing Personal Data (GDPR)</h3>
              <p className="text-lg leading-relaxed mb-3">We process your Personal Data under the following lawful bases:</p>
              <ul className="list-disc pl-6 space-y-2 text-lg">
                <li><strong>Consent:</strong> When you have given clear permission for us to process your data</li>
                <li><strong>Contract:</strong> When processing is necessary to fulfill a contract</li>
                <li><strong>Legal Obligation:</strong> When we are legally required to process your data</li>
                <li><strong>Legitimate Interests:</strong> When processing is necessary for our legitimate business interests</li>
              </ul>
            </div>

            <div>
              <h3 className="font-display font-semibold text-xl text-foreground mb-3 mt-6">California Privacy Rights (CCPA / CPRA)</h3>
              <p className="text-lg leading-relaxed mb-3">If you are a California resident, you have additional rights including:</p>
              <ul className="list-disc pl-6 space-y-2 text-lg">
                <li>The right to know what personal information we collect, use, disclose, or sell</li>
                <li>The right to delete your personal information</li>
                <li>The right to opt-out of the sale or sharing of your personal data</li>
                <li>The right to non-discrimination for exercising your rights</li>
              </ul>
            </div>

            <div>
              <h2 className="font-display font-semibold text-2xl md:text-3xl text-primary mb-4 mt-8">Changes to this Privacy Policy</h2>
              <p className="text-lg leading-relaxed">
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the date at the top of this Privacy Policy.
              </p>
            </div>

            <div>
              <h2 className="font-display font-semibold text-2xl md:text-3xl text-primary mb-4 mt-8">Contact Us</h2>
              <p className="text-lg leading-relaxed">
                If you have any questions about this Privacy Policy, You can contact us by visiting our{" "}
                <a href="/contact" className="text-primary hover:underline">contact page</a>.
              </p>
            </div>
          </div>
        </div>
      </section>
      
      <Footer />
    </div>
  );
}
